In [1]:
from IPython.display import HTML

HTML('''<script>
code_show=true; 
function code_toggle() {
 if (code_show){
 $('div.input').hide();
 } else {
 $('div.input').show();
 }
 code_show = !code_show
} 
$( document ).ready(code_toggle);
</script>
<form action="javascript:code_toggle()"><input type="submit" value="Click here to toggle on/off the raw code."></form>''')

## Daily Volume for CME Energy Options Contracts for 11/02/2020
#### Below is a list of CME Energy Options contracts that have at least 100 lots of volume.
There are not many contracts that have significant volume

In [3]:
import pandas as pd


df_cme_volume = pd.read_csv('cme_daily_volume_20201102.csv')
df_cme_volume['vol'] = pd.to_numeric(df_cme_volume.Volume.str.replace(',',''))
df_cme_volume['oi'] = pd.to_numeric(df_cme_volume['Open Interest'].str.replace(',',''))
df_cme_volume2 = df_cme_volume[(~df_cme_volume.Name.isna())]
tests = [
    df_cme_volume2.vol>10000,
    ~df_cme_volume2.Type.str.lower().str.contains('future'),
]
df_cme_volume2 = df_cme_volume2[[all(v) for v in zip(*tests)]]


df_cme_vol2 = df_cme_volume[
    (df_cme_volume.Type=='Options') & 
    (df_cme_volume.vol>=100)
].sort_values('vol',ascending=False)

pd.set_option('display.max_colwidth', 0)
df_cme_vol3 = df_cme_vol2[[c for c in df_cme_vol2 if c not in ['oi','vol']]]
df_cme_vol3

,Name,Type,Globex,Open OutCry,Clear Port,Volume,Open Interest,Change
61,Crude Oil Option,Options,"153,647",0.0,"15,219","168,866","1,914,123","33,392"
162,Natural Gas Option (European),Options,"28,351",0.0,"49,894","78,245","2,442,035","17,978"
400,WTI Crude Oil 1 Month Calendar Spread Option,Options,650,0.0,"3,200","3,850","440,725","3,150"
27,Brent Crude Oil Futures-Style Margin Option,Options,823,0.0,"2,300","3,123","50,206",621
179,Light Sweet Crude Oil (WTI) Financial 1 Month Spread Option,Options,0,0.0,"3,000","3,000","238,520","3,000"
24,Brent Last Day Financial (European) Option,Options,0,0.0,"2,600","2,600","99,121",0
159,Natural Gas Option (American),Options,"1,997",0.0,0,"1,997","40,186",787
67,Crude Oil Weekly Options - Week 1,Options,"1,193",0.0,0,"1,193","3,214",439
64,Light Sweet Crude Oil European Financial Option,Options,0,0.0,520,520,"37,051",424
298,NY Harbor ULSD Option,Options,58,0.0,450,508,"21,052",235
362,RBOB Gasoline Option,Options,468,0.0,0,468,"9,029",52
44,Coal (API 2) cif ARA (Argus/McCloskey) Option,Options,0,0.0,450,450,"4,287",-180
247,Mont Belvieu Normal Butane (OPIS) Average Price Option,Options,0,0.0,300,300,420,150
404,WTI Average Price Option,Options,0,0.0,200,200,"252,980",200
70,Crude Oil Weekly Options - Week 2,Options,150,0.0,0,150,602,142
294,NY Harbor ULSD Average Price Option,Options,0,0.0,145,145,"7,401",25

In [4]:
!jupyter nbconvert --to HTML Untitled.ipynb

[NbConvertApp] Converting notebook Untitled.ipynb to HTML
[NbConvertApp] Writing 283784 bytes to Untitled.html