In [654]:
import zipfile
import glob
import pandas as pd
import numpy as np

from argparse import ArgumentParser
from argparse import RawDescriptionHelpFormatter
import sys
import os
if  not './' in sys.path:
    sys.path.append('./')
if  not '../' in sys.path:
    sys.path.append('../')

from barchartacs import build_db
from barchartacs import db_info
import plotly.graph_objs as go
from plotly.offline import  init_notebook_mode, iplot
init_notebook_mode(connected=True)
import plotly.tools as tls
from IPython import display

import datetime
import io
from tqdm import tqdm,tqdm_notebook
from barchartacs import pg_pandas as pg
import mibian
import py_vollib
import importlib
from py_vollib import black
from py_vollib.black import implied_volatility

# importlib.reload(db_info)

In [599]:
#!pip install py_vollib

Requirement already satisfied: py_vollib in /Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages (1.0.1)
Requirement already satisfied: numpy in /Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages (from py_vollib) (1.16.3)
Requirement already satisfied: py-lets-be-rational in /Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages (from py_vollib) (1.0.1)
Requirement already satisfied: pandas in /Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages (from py_vollib) (0.24.2)
Requirement already satisfied: scipy in /Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages (from py_vollib) (1.1.0)
Requirement already satisfied: simplejson in /Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages (from py_vollib) (3.16.0)
Requirement already satisfied: pytz>=2011k in /Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages (from pandas->py_vollib) (2018.4)
Requirement already satisfied: python-dateutil>=2.5.0 in /Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages (from pandas->py_vollib) (2.7.3)
Requirement already satisfied: six>=1.5 in /Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages (from python-dateutil>=2.5.0->pandas->py_vollib) (1.11.0)
tensorflow 1.10.1 has requirement numpy<=1.14.5,>=1.13.3, but you'll have numpy 1.16.3 which is incompatible.
spacy 2.0.16 has requirement regex==2018.01.10, but you'll have regex 2018.11.22 which is incompatible.
dash 0.38.0rc1 has requirement dash-table==3.3.0, but you'll have dash-table 3.2.0 which is incompatible.
You are using pip version 10.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

In [554]:
def plotly_plot(df_in,x_column,plot_title=None,
                y_left_label=None,y_right_label=None,
                bar_plot=False,figsize=(16,10),
                number_of_ticks_display=20,
                yaxis2_cols=None):
    ya2c = [] if yaxis2_cols is None else yaxis2_cols
    ycols = [c for c in df_in.columns.values if c != x_column]
    # create tdvals, which will have x axis labels
    td = list(df_in[x_column]) 
    nt = len(df_in)-1 if number_of_ticks_display > len(df_in) else number_of_ticks_display
    spacing = len(td)//nt
    tdvals = td[::spacing]
    
    # create data for graph
    data = []
    # iterate through all ycols to append to data that gets passed to go.Figure
    for ycol in ycols:
        if bar_plot:
            b = go.Bar(x=td,y=df_in[ycol],name=ycol,yaxis='y' if ycol not in ya2c else 'y2')
        else:
            b = go.Scatter(x=td,y=df_in[ycol],name=ycol,yaxis='y' if ycol not in ya2c else 'y2')
        data.append(b)

    # create a layout
    layout = go.Layout(
        title=plot_title,
        xaxis=dict(
            ticktext=tdvals,
            tickvals=tdvals,
            tickangle=45,
            type='category'),
        yaxis=dict(
            title='y main' if y_left_label is None else y_left_label
        ),
        yaxis2=dict(
            title='y alt' if y_right_label is None else y_right_label,
            overlaying='y',
            side='right'),
        margin=go.Margin(
            b=100
        )        
    )

    fig = go.Figure(data=data,layout=layout)
    return fig

In [5]:
pga = db_info.get_db_info()
opttab = 'sec_schema.options_table'
futtab = 'sec_schema.underlying_table'

  sec_db

### get data from sql

In [587]:
osql = f"select * from {opttab} where substring(settle_date::text,1,5)='20150';"
dfo = pga.get_sql(osql)
usql = f"select * from {futtab} where substring(settle_date::text,1,5)='20150';"
dfu = pga.get_sql(usql)

In [590]:
print(dfo.shape,dfu.shape)
display.display(dfo.head())
display.display(dfu.head())

(1998090, 11) (471102, 10)

,symbol,strike,pc,settle_date,open,high,low,close,adj_close,volume,open_interest
0,CBG15,1000.0,C,20150102,0.0,0.01,0.01,0.01,0.01,0,3756
1,CBG15,1000.0,P,20150102,0.0,43.58,43.58,43.58,43.58,0,465
2,CBG15,1005.0,C,20150102,0.0,0.01,0.01,0.01,0.01,0,300
3,CBG15,1005.0,P,20150102,0.0,44.08,44.08,44.08,44.08,0,0
4,CBG15,1010.0,C,20150102,0.0,0.01,0.01,0.01,0.01,0,150

,symbol,settle_date,contract_num,open,high,low,close,adj_close,volume,open_interest
0,A6Z99,20150102,21,0.81779,0.81831,0.80773,0.80883,0.80883,0,0
1,A6H15,20150102,1,0.81270,0.81430,0.80350,0.80720,0.80720,34353,119037
2,A6M15,20150102,2,0.80480,0.80510,0.79960,0.80230,0.80230,24,190
3,A6U15,20150102,3,0.00000,0.79780,0.79780,0.79780,0.79780,0,36
4,A6Z15,20150102,4,0.00000,0.79390,0.79390,0.79390,0.79390,0,17

In [591]:
df = dfo.merge(dfu,how='inner',on=['symbol','settle_date'])

In [593]:
print(df.shape)
df.head()

(1994858, 19)

,symbol,strike,pc,settle_date,open_x,high_x,low_x,close_x,adj_close_x,volume_x,open_interest_x,contract_num,open_y,high_y,low_y,close_y,adj_close_y,volume_y,open_interest_y
0,CBG15,1000.0,C,20150102,0.0,0.01,0.01,0.01,0.01,0,3756,1,58.02,58.54,55.48,56.42,56.42,148140,265279
1,CBG15,1000.0,P,20150102,0.0,43.58,43.58,43.58,43.58,0,465,1,58.02,58.54,55.48,56.42,56.42,148140,265279
2,CBG15,1005.0,C,20150102,0.0,0.01,0.01,0.01,0.01,0,300,1,58.02,58.54,55.48,56.42,56.42,148140,265279
3,CBG15,1005.0,P,20150102,0.0,44.08,44.08,44.08,44.08,0,0,1,58.02,58.54,55.48,56.42,56.42,148140,265279
4,CBG15,1010.0,C,20150102,0.0,0.01,0.01,0.01,0.01,0,150,1,58.02,58.54,55.48,56.42,56.42,148140,265279

### create pivot of strikes per day

In [596]:

df2 = df[['symbol','contract_num','pc','settle_date','strike','close_x','close_y']]
df2 = df2[(df2.pc=='C') & (df2.symbol.str.slice(0,2).isin(['CL']))]
df2 = df2[df2.contract_num==2]
df2.strike = df2.strike/10
phigh = df2.close_y.max()
plow = df2.close_y.min()
high_strike = round(phigh * 1.2)
low_strike = round(plow * .8)
print(high_strike,low_strike,df2.strike.max(),df2.strike.min())
df2 = df2[(df2.strike>=low_strike) & (df2.strike<=high_strike)]
df2['symset'] = df2.symbol + "_" + df2.settle_date.astype(str)
df3 = df2.pivot(index='symset',columns='strike',values='close_x')
df3['symset'] = df3.index.values
df3.index.name=None
df3.index = list(range(len(df3)))
df3.columns.name = None
df3['symset_array'] = df3.symset.str.split('_')
df3['symbol'] = df3.symset_array.apply(lambda a:a[0])
df3['settle_date'] = df3.symset_array.apply(lambda a:a[1])
cols_in_order = ['symbol','settle_date'] + [c for c in df3.columns.values if c not in ['symbol','settle_date','symset','symset_array']]
df3 = df3[cols_in_order]
df3.settle_date = df3.settle_date.astype(str).astype(int)
df3.head()

74.0 31.0 200.0 25.0

,symbol,settle_date,31.0,31.5,32.0,33.5,34.0,35.0,35.5,36.0,...,69.5,70.0,70.5,71.0,71.5,72.0,72.5,73.0,73.5,74.0
0,CLH15,20150102,NaN,NaN,NaN,NaN,NaN,18.29,NaN,NaN,...,0.28,0.26,0.24,0.23,0.21,0.20,0.18,0.17,0.16,0.15
1,CLH15,20150105,NaN,NaN,NaN,NaN,NaN,15.80,NaN,NaN,...,0.18,0.17,0.16,0.15,0.14,0.13,0.13,0.12,0.11,0.11
2,CLH15,20150106,NaN,NaN,NaN,NaN,NaN,13.74,NaN,NaN,...,0.11,0.11,0.10,0.10,0.09,0.09,0.08,0.08,0.07,0.07
3,CLH15,20150107,NaN,NaN,NaN,NaN,NaN,14.25,NaN,NaN,...,0.10,0.09,0.08,0.08,0.07,0.07,0.07,0.06,0.06,0.06
4,CLH15,20150108,NaN,NaN,NaN,NaN,NaN,14.40,NaN,NaN,...,0.08,0.08,0.07,0.07,0.07,0.06,0.06,0.06,0.05,0.05

In [597]:

mcols = ['symbol','settle_date']
df4 = dfu[mcols + ['close']]
df5 = df3.merge(df4,on=mcols,how='inner')
first_cols = ['symbol','settle_date','close']
cols_in_order = first_cols + [c for c in df5.columns.values if c not in first_cols]
df5 = df5[cols_in_order]
df5

,symbol,settle_date,close,31.0,31.5,32.0,33.5,34.0,35.0,35.5,...,69.5,70.0,70.5,71.0,71.5,72.0,72.5,73.0,73.5,74.0
0,CLH15,20150102,53.11,NaN,NaN,NaN,NaN,NaN,18.29,NaN,...,0.28,0.26,0.24,0.23,0.21,0.20,0.18,0.17,0.16,0.15
1,CLH15,20150105,50.52,NaN,NaN,NaN,NaN,NaN,15.80,NaN,...,0.18,0.17,0.16,0.15,0.14,0.13,0.13,0.12,0.11,0.11
2,CLH15,20150106,48.46,NaN,NaN,NaN,NaN,NaN,13.74,NaN,...,0.11,0.11,0.10,0.10,0.09,0.09,0.08,0.08,0.07,0.07
3,CLH15,20150107,49.08,NaN,NaN,NaN,NaN,NaN,14.25,NaN,...,0.10,0.09,0.08,0.08,0.07,0.07,0.07,0.06,0.06,0.06
4,CLH15,20150108,49.28,NaN,NaN,NaN,NaN,NaN,14.40,NaN,...,0.08,0.08,0.07,0.07,0.07,0.06,0.06,0.06,0.05,0.05
5,CLH15,20150109,48.99,NaN,NaN,NaN,NaN,NaN,14.12,NaN,...,0.07,0.07,0.07,0.06,0.06,0.06,0.05,0.05,0.05,0.05
6,CLH15,20150112,46.76,NaN,NaN,NaN,NaN,NaN,11.94,NaN,...,0.04,0.04,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.03
7,CLH15,20150113,46.51,NaN,NaN,NaN,NaN,NaN,11.73,NaN,...,0.04,0.04,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.02
8,CLH15,20150114,48.96,NaN,NaN,NaN,NaN,NaN,14.07,NaN,...,0.07,0.06,0.06,0.06,0.05,0.05,0.05,0.04,0.04,0.04
9,CLH15,20150115,46.73,NaN,NaN,NaN,NaN,NaN,11.96,NaN,...,0.05,0.05,0.05,0.04,0.04,0.04,0.04,0.04,0.03,0.03
10,CLH15,20150116,49.13,NaN,NaN,NaN,NaN,NaN,14.26,NaN,...,0.07,0.07,0.06,0.06,0.05,0.05,0.05,0.04,0.04,0.04
11,CLH15,20150120,46.47,NaN,NaN,NaN,NaN,NaN,11.65,NaN,...,0.03,0.03,0.03,0.03,0.03,0.02,0.02,0.02,0.02,0.02
12,CLJ15,20150121,48.43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.16,0.15,0.14,0.13,0.12,0.11,0.11,0.10,0.09,0.09
13,CLJ15,20150122,46.98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.13,0.12,0.11,0.11,0.10,0.09,0.09,0.08,0.08,0.07
14,CLJ15,20150123,46.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.11,0.10,0.10,0.09,0.08,0.08,0.07,0.07,0.07,0.06
15,CLJ15,20150126,45.88,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.09,0.08,0.08,0.07,0.07,0.06,0.06,0.06,0.05,0.05
16,CLJ15,20150127,46.95,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.09,0.08,0.08,0.07,0.07,0.06,0.06,0.06,0.05,0.05
17,CLJ15,20150128,45.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.07,0.06,0.06,0.06,0.05,0.05,0.05,0.04,0.04,0.04
18,CLJ15,20150129,45.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.06,0.05,0.05,0.05,0.04,0.04,0.04,0.04,0.03,0.03
19,CLJ15,20150130,48.99,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.17,0.16,0.15,0.14,0.13,0.12,0.12,0.11,0.10,0.10
20,CLJ15,20150202,50.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.20,0.19,0.18,0.17,0.16,0.15,0.14,0.13,0.12,0.11
21,CLJ15,20150203,53.86,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.52,0.49,0.46,0.43,0.40,0.38,0.36,0.33,0.32,0.30
22,CLJ15,20150204,49.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.22,0.21,0.20,0.18,0.17,0.16,0.15,0.15,0.14,0.13
23,CLJ15,20150205,51.31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.32,0.30,0.28,0.26,0.24,0.23,0.21,0.20,0.19,0.18
24,CLJ15,20150206,52.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.33,0.31,0.28,0.26,0.24,0.23,0.21,0.20,0.19,0.17
25,CLJ15,20150209,53.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.25,0.23,0.21,0.19,0.18,0.16,0.15,0.14,0.13,0.12
26,CLJ15,20150210,50.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.14,0.13,0.12,0.11,0.10,0.09,0.09,0.08,0.08,0.07
27,CLJ15,20150211,49.78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.10,0.09,0.09,0.08,0.08,0.07,0.07,0.06,0.06,0.06
28,CLJ15,20150212,52.16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.16,0.14,0.13,0.12,0.11,0.11,0.10,0.09,0.09,0.08
29,CLJ15,20150213,53.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.19,0.18,0.17,0.16,0.15,0.14,0.13,0.12,0.11,0.11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158,CLV15,20150819,41.27,NaN,9.83,NaN,7.89,7.42,6.48,6.03,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
159,CLV15,20150820,41.32,NaN,9.87,NaN,7.92,7.45,6.51,6.05,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
160,CLX15,20150821,41.19,NaN,NaN,NaN,NaN,NaN,6.84,NaN,...,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.01,0.01,0.01
161,CLX15,20150824,38.93,NaN,NaN,NaN,NaN,NaN,5.11,NaN,...,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.01,0.01,0.01
162,CLX15,20150825,39.95,NaN,NaN,NaN,NaN,NaN,5.88,NaN,...,0.02,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
163,CLX15,20150826,39.37,8.74,NaN,NaN,NaN,NaN,5.39,NaN,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
164,CLX15,20150827,43.37,12.53,NaN,NaN,NaN,NaN,8.83,NaN,...,0.03,0.03,0.03,0.03,0.02,0.02,0.02,0.02,0.02,0.02
165,CLX15,20150828,45.98,15.09,NaN,NaN,NaN,NaN,11.28,NaN,...,0.07,0.07,0.06,0.06,0.05,0.05,0.05,0.04,0.04,0.04
166,CLX15,20150831,49.93,19.00,NaN,NaN,NaN,NaN,15.10,NaN,...,0.18,0.17,0.16,0.15,0.14,0.13,0.12,0.11,0.11,0.10
167,CLX15,20150901,46.02,15.15,NaN,NaN,NaN,NaN,11.38,NaN,...,0.08,0.07,0.07,0.06,0.06,0.05,0.05,0.05,0.05,0.04
168,CLX15,20150902,46.86,15.95,NaN,NaN,NaN,NaN,12.11,NaN,...,0.07,0.06,0.06,0.05,0.05,0.05,0.04,0.04,0.04,0.04
169,CLX15,20150903,47.32,16.39,NaN,NaN,NaN,NaN,12.53,NaN,...,0.06,0.05,0.05,0.05,0.05,0.04,0.04,0.04,0.04,0.04
170,CLX15,20150904,46.63,15.70,NaN,NaN,NaN,NaN,11.84,NaN,...,0.04,0.04,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.02
171,CLX15,20150908,46.59,15.65,NaN,NaN,NaN,NaN,11.77,NaN,...,0.04,0.04,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.02
172,CLX15,20150909,44.80,13.87,NaN,NaN,NaN,NaN,10.04,NaN,...,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.01,0.01
173,CLX15,20150910,46.44,15.49,NaN,NaN,NaN,NaN,11.61,NaN,...,0.03,0.03,0.03,0.03,0.02,0.02,0.02,0.02,0.02,0.02
174,CLX15,20150911,45.16,14.21,NaN,NaN,NaN,NaN,10.34,NaN,...,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.01,0.01
175,CLX15,20150914,44.43,13.48,NaN,NaN,NaN,NaN,9.62,NaN,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
176,CLX15,20150915,45.00,14.04,NaN,NaN,NaN,NaN,10.15,NaN,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
177,CLX15,20150916,47.51,16.53,NaN,NaN,NaN,NaN,12.59,NaN,...,0.03,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.01,0.01
178,CLX15,20150917,47.20,16.21,NaN,NaN,NaN,NaN,12.25,NaN,...,0.02,0.02,0.02,0.02,0.02,0.01,0.01,0.01,0.01,0.01
179,CLX15,20150918,45.02,14.04,NaN,NaN,NaN,NaN,10.12,NaN,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
180,CLX15,20150921,46.96,15.97,NaN,NaN,NaN,NaN,12.01,NaN,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
181,CLX15,20150922,46.36,15.37,NaN,NaN,NaN,NaN,11.43,NaN,...,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01,0.01
182,CLZ15,20150923,45.10,NaN,NaN,13.32,NaN,NaN,10.56,NaN,...,0.05,0.04,0.04,0.04,0.03,0.03,0.03,0.03,0.03,0.03
183,CLZ15,20150924,45.48,NaN,NaN,13.68,NaN,NaN,10.89,NaN,...,0.04,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.03
184,CLZ15,20150925,46.19,NaN,NaN,14.34,NaN,NaN,11.51,NaN,...,0.04,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.03,0.02
185,CLZ15,20150928,44.87,NaN,NaN,13.05,NaN,NaN,10.25,NaN,...,0.03,0.03,0.03,0.03,0.03,0.02,0.02,0.02,0.02,0.02
186,CLZ15,20150929,45.64,NaN,NaN,13.79,NaN,NaN,10.96,NaN,...,0.04,0.04,0.04,0.03,0.03,0.03,0.03,0.03,0.03,0.02
187,CLZ15,20150930,45.56,NaN,NaN,13.68,NaN,NaN,10.82,NaN,...,0.03,0.03,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02

In [198]:
w1 = "char_length(symbol)=5 and substring(symbol,1,2)='CL' and substring(symbol,4,2)::int>='15'"

osql = f"select * from {opttab} where {w1};"
dfo2 = pga.get_sql(osql)

In [594]:
df_expiry_dates = dfo2[['symbol','settle_date']].groupby('symbol',as_index=False).max()

In [595]:
df_expiry_dates.head()

  symbol  settle_date
0  CLF15     20141216
1  CLF16     20151216
2  CLF17     20161215
3  CLF18     20171214
4  CLF19     20171229

In [229]:
df5['expiry'] = df5[['symbol']].merge(df_expiry_dates,on='symbol',how='inner').settle_date
df6 = df5.copy()
df6['syear'] = df6.settle_date.astype(str).str.slice(0,4).astype(int)
df6['smon'] = df6.settle_date.astype(str).str.slice(4,6).astype(int)
df6['sday'] = df6.settle_date.astype(str).str.slice(6,8).astype(int)
df6['eyear'] = df6.expiry.astype(str).str.slice(0,4).astype(int)
df6['emon'] = df6.expiry.astype(str).str.slice(4,6).astype(int)
df6['eday'] = df6.expiry.astype(str).str.slice(6,8).astype(int)
df6['sdatetime'] = df6.apply(lambda r:datetime.datetime(r.syear,r.smon,r.sday),axis=1)
df6['edatetime'] = df6.apply(lambda r:datetime.datetime(r.eyear,r.emon,r.eday),axis=1)
df6['dte'] = df6.edatetime - df6.sdatetime
df6.dte = df6.dte.dt.days
on_cols = ['symbol','settle_date']
df5['dte'] = df5[on_cols].merge(df6[on_cols+['dte']],on=on_cols,how='inner').dte

In [230]:
df5.head()

,symbol,settle_date,close,40.0,41.0,42.0,43.0,44.0,44.5,45.0,...,69.5,70.0,70.5,71.0,71.5,72.0,72.5,73.0,expiry,dte
0,CLM15,20150401,51.75,12.21,11.31,10.43,9.57,8.73,8.32,7.92,...,0.13,0.12,0.11,0.10,0.09,0.09,0.08,0.08,20150514,43
1,CLM15,20150402,50.60,11.17,10.29,9.43,8.59,7.78,7.38,7.00,...,0.10,0.09,0.09,0.08,0.08,0.08,0.07,0.07,20150514,42
2,CLM15,20150406,53.57,13.84,12.90,11.97,11.06,10.16,9.72,9.29,...,0.12,0.11,0.11,0.10,0.09,0.09,0.08,0.08,20150514,38
3,CLM15,20150407,55.23,15.41,14.44,13.49,12.55,11.62,11.15,10.70,...,0.13,0.12,0.11,0.11,0.10,0.09,0.09,0.08,20150514,37
4,CLM15,20150408,51.87,12.18,11.24,10.33,9.44,8.56,8.14,7.72,...,0.06,0.06,0.05,0.05,0.05,0.05,0.04,0.04,20150514,36

In [275]:
non_strikes = ['symbol','settle_date','close','expiry','dte']
strikes = list(set(df5.columns.values).difference(set(non_strikes)))
df6 = df5.copy()
df6 = df6.rename(columns = {c:str(c)+'s' for c in strikes})
strikes = list(set(df6.columns.values).difference(set(non_strikes)))
r = df6.iloc[0]
opt_info = [r.close,float(strikes[0][:-1]),2,r.dte]
r['close'],r[strikes[0]]
mibian.BS(opt_info, callPrice=r[strikes[0]]).impliedVolatility

47.8515625

#### get implied vols

In [287]:
non_strikes = ['symbol','settle_date','close','expiry','dte']
strikes = list(set(df5.columns.values).difference(set(non_strikes)))
df6 = df5.copy()
df6 = df6.rename(columns = {c:str(c)+'s' for c in strikes})
strikes = list(set(df6.columns.values).difference(set(non_strikes)))

print(strikes)
for strike in tqdm_notebook(strikes):
    s = float(strike.replace('s',''))
    df6[f"{s}c"] = df6[non_strikes + [strike]].apply(
        lambda r: -1 if np.isnan(r[strike]) else mibian.BS([r.close,s,2,r.dte], callPrice=r[strike]).impliedVolatility
        ,axis=1)

['72.0s', '64.0s', '58.0s', '55.5s', '45.5s', '56.0s', '40.0s', '72.5s', '64.5s', '71.0s', '46.5s', '63.0s', '73.0s', '44.0s', '48.0s', '54.0s', '49.0s', '57.5s', '54.5s', '55.0s', '56.5s', '66.5s', '63.5s', '65.0s', '51.5s', '62.0s', '61.5s', '47.0s', '62.5s', '49.5s', '66.0s', '71.5s', '48.5s', '70.0s', '65.5s', '46.0s', '43.0s', '68.5s', '53.0s', '53.5s', '47.5s', '50.0s', '60.0s', '67.0s', '50.5s', '52.0s', '61.0s', '68.0s', '60.5s', '57.0s', '52.5s', '42.0s', '59.0s', '59.5s', '44.5s', '41.0s', '51.0s', '70.5s', '67.5s', '69.0s', '58.5s', '69.5s', '45.0s']

HBox(children=(IntProgress(value=0, max=63), HTML(value='')))

In [495]:
df7 = df6[non_strikes + [c.replace('s','c') for c in strikes]]

In [496]:
df7.head()

,symbol,settle_date,close,expiry,dte,68.0c,45.5c,47.5c,60.5c,55.0c,...,60.0c,71.0c,67.0c,53.5c,53.0c,67.5c,58.0c,69.5c,59.5c,55.5c
0,CLM15,20150401,51.75,20150514,43,45.898438,52.246094,50.537109,43.701172,45.043945,...,43.701172,46.875000,45.410156,45.898438,46.264648,45.898438,43.945312,46.875000,43.701172,44.921875
1,CLM15,20150402,50.60,20150514,42,47.851562,52.490234,50.781250,44.189453,45.288086,...,44.189453,48.828125,46.875000,45.898438,46.142578,47.363281,44.433594,46.875000,42.968750,44.921875
2,CLM15,20150406,53.57,20150514,38,43.457031,51.757812,48.828125,41.015625,42.968750,...,41.015625,46.875000,42.968750,44.189453,44.677734,42.968750,41.625977,43.945312,41.137695,42.846680
3,CLM15,20150407,55.23,20150514,37,40.527344,50.292969,48.339844,38.818359,41.625977,...,38.696289,42.480469,39.794922,42.968750,43.457031,39.550781,39.550781,41.015625,39.062500,41.259766
4,CLM15,20150408,51.87,20150514,36,42.968750,50.781250,48.217773,40.039062,41.748047,...,40.039062,46.875000,42.968750,42.968750,43.212891,42.968750,40.283203,44.921875,39.062500,41.625977

#### get deltas

In [497]:
df8 = df7.copy()
non_strikes = ['symbol','settle_date','close','expiry','dte']
strikes = list(set(df8.columns.values).difference(set(non_strikes)))

print(strikes)
for strike in tqdm_notebook(strikes):
    s = float(strike.replace('c',''))
    df8[f"{s}c"] = df8[non_strikes + [strike]].apply(
        lambda r: -1 if np.isnan(r[strike]) else mibian.BS([r.close,s,2,r.dte], volatility=r[strike]).callDelta
        ,axis=1)

['68.0c', '45.5c', '47.5c', '60.5c', '55.0c', '64.5c', '70.0c', '63.5c', '62.0c', '57.5c', '54.5c', '40.0c', '64.0c', '66.5c', '51.0c', '46.0c', '49.5c', '69.0c', '65.5c', '73.0c', '47.0c', '48.5c', '61.0c', '65.0c', '58.5c', '63.0c', '46.5c', '52.5c', '56.0c', '68.5c', '41.0c', '42.0c', '72.5c', '54.0c', '50.0c', '72.0c', '57.0c', '70.5c', '66.0c', '50.5c', '45.0c', '48.0c', '52.0c', '71.5c', '49.0c', '44.0c', '43.0c', '59.0c', '44.5c', '51.5c', '56.5c', '61.5c', '62.5c', '60.0c', '71.0c', '67.0c', '53.5c', '53.0c', '67.5c', '58.0c', '69.5c', '59.5c', '55.5c']

HBox(children=(IntProgress(value=0, max=63), HTML(value='')))

In [498]:
df8.head()

,symbol,settle_date,close,expiry,dte,68.0c,45.5c,47.5c,60.5c,55.0c,...,60.0c,71.0c,67.0c,53.5c,53.0c,67.5c,58.0c,69.5c,59.5c,55.5c
0,CLM15,20150401,51.75,20150514,43,0.050532,0.794051,0.723860,0.170859,0.381547,...,0.185273,0.030702,0.058911,0.453279,0.477644,0.055595,0.253063,0.041118,0.200549,0.358918
1,CLM15,20150402,50.60,20150514,42,0.042221,0.757604,0.679573,0.135278,0.326007,...,0.147683,0.025687,0.047302,0.395384,0.419530,0.044660,0.207558,0.028586,0.153169,0.303179
2,CLM15,20150406,53.57,20150514,38,0.053037,0.858513,0.803809,0.201200,0.457921,...,0.219278,0.038109,0.063110,0.537868,0.563846,0.056733,0.305408,0.040021,0.239194,0.431786
3,CLM15,20150407,55.23,20150514,37,0.062790,0.903710,0.857642,0.254883,0.545005,...,0.276152,0.037993,0.074175,0.623941,0.648661,0.064997,0.378449,0.046569,0.301430,0.517545
4,CLM15,20150408,51.87,20150514,36,0.027152,0.819563,0.748552,0.126027,0.357074,...,0.140210,0.020401,0.034791,0.441489,0.469546,0.030762,0.210670,0.023329,0.148879,0.331065

#### do implied vol interpolation to find vol at option that is 10% out of the money

In [513]:
non_strikes = ['symbol','settle_date','close','expiry','dte']
strikes = list(set(df7.columns.values).difference(set(non_strikes)))
dft =df7[strikes].iloc[:1]
dft = dft.T.sort_index()
dft.index = [float(s.replace('c','')) for s in dft.index]
dft.columns = ['imp']
dft.head()

            imp
40.0  56.640625
41.0  55.664062
42.0  55.175781
43.0  54.199219
44.0  53.466797

In [515]:
a

array([36.05 , 38.625, 41.2  , 43.775, 46.35 , 48.925, 51.5  , 54.075,
       56.65 , 59.225, 61.8  , 64.375, 66.95 ])

In [518]:
v = 51.5
a = np.arange(.7,1.3,.05) * v
a = a.round(6)
for x in a:
    dft.loc[x,'imp'] = None
dft = dft.sort_index()
dft['imp2'] = dft.imp.interpolate(method='polynomial', order=2)
dft['skew'] = (dft.imp2 - dft.loc[v].imp2).round(4)
dft['money'] = (dft.index / v - 1)
dft.money = dft.money.round(4)
dft[dft.index.isin(a)]
# a = np.array(sorted([float(s.replace('c','')) for s in strikes]))
# b = 
# m = np.abs(a - t).argmin()
# pair =(a[m],a[m+1]) if a[m]<t else (a[m-1],a[m])

# print(t,pair)
# pd.DataFrame({'a':a})

        imp       imp2    skew  money
36.050  NaN        NaN     NaN  -0.30
38.625  NaN        NaN     NaN  -0.25
41.200  NaN  55.550414  8.1049  -0.20
43.775  NaN  53.647691  6.2022  -0.15
46.350  NaN  51.418449  3.9729  -0.10
48.925  NaN  49.245840  1.8003  -0.05
51.500  NaN  47.445534  0.0000   0.00
54.075  NaN  45.621523 -1.8240   0.05
56.650  NaN  44.362435 -3.0831   0.10
59.225  NaN  43.219228 -4.2263   0.15
61.800  NaN  43.703662 -3.7419   0.20
64.375  NaN  43.949825 -3.4957   0.25
66.950  NaN  45.396873 -2.0487   0.30

In [378]:
display(df2.head())
display(df_expiry_dates.head())

,symbol,contract_num,pc,settle_date,strike,close_x,close_y,symset
8835,CLM15,2,C,20150401,40.0,12.21,51.75,CLM15_20150401
8838,CLM15,2,C,20150401,41.0,11.31,51.75,CLM15_20150401
8841,CLM15,2,C,20150401,42.0,10.43,51.75,CLM15_20150401
8844,CLM15,2,C,20150401,43.0,9.57,51.75,CLM15_20150401
8847,CLM15,2,C,20150401,44.0,8.73,51.75,CLM15_20150401

  symbol  settle_date
0  CLF15     20141216
1  CLF16     20151216
2  CLF17     20161215
3  CLF18     20171214
4  CLF19     20171229

In [678]:
#CL,Q2019,560P,07/02/2019,0.6,1.61,0.54,1.54,1997,4465
F = 56.25
K = 56
sigma = .366591539
flag = 'p'
t = 15/365.0
r = .025
discounted_call_price = black.black(flag, F, K, t, r, sigma)
dcp = 1.54
ivpy = implied_volatility.implied_volatility(dcp, F, K, r, t, flag)
ivmn = mibian.BS([F,K,2.5,15], callPrice=dcp).impliedVolatility
discounted_call_price,ivpy,ivmn

(1.5399999992892466, 0.36659153915713766, 30.517578125)

In [679]:
USE_PYVOL = True
contract='CLM15'
df9 = df2[df2.symbol==contract]
df9 = df9.merge(df_expiry_dates.rename(columns={'settle_date':'expiry'}),on='symbol',how='inner')
df9['syear'] = df9.settle_date.astype(str).str.slice(0,4).astype(int)
df9['smon'] = df9.settle_date.astype(str).str.slice(4,6).astype(int)
df9['sday'] = df9.settle_date.astype(str).str.slice(6,8).astype(int)
df9['eyear'] = df9.expiry.astype(str).str.slice(0,4).astype(int)
df9['emon'] = df9.expiry.astype(str).str.slice(4,6).astype(int)
df9['eday'] = df9.expiry.astype(str).str.slice(6,8).astype(int)
df9['sdatetime'] = df9.apply(lambda r:datetime.datetime(r.syear,r.smon,r.sday),axis=1)
df9['edatetime'] = df9.apply(lambda r:datetime.datetime(r.eyear,r.emon,r.eday),axis=1)
df9['dte'] = df9.edatetime - df9.sdatetime
df9.dte = df9.dte.dt.days
df9 = df9[['symbol','settle_date','pc','contract_num','strike','close_x','close_y','dte']]
df10 = df9.iloc[:len(df9)]
df10.index = list(range(len(df10)))
lam_pyvol = lambda r:implied_volatility.implied_volatility(r.close_x,r.close_y,r.strike,.02,r.dte/365, r.pc.lower())
lam_mibian = lambda r:mibian.BS([r.close_y,r.strike,2,r.dte], callPrice=r.close_x).impliedVolatility
n = 100
for i in tqdm_notebook(np.arange(0,len(df10)-n,n)):
    if USE_PYVOL:
        df10.loc[i:i+n,'iv'] = df10.loc[i:i+n].apply(lam_pyvol,axis=1)
    else:
        df10.loc[i:i+n,'iv'] = df10.loc[i:i+n].apply(lam_mibian,axis=1)
#     ivv = implied_volatility.implied_volatility(discounted_call_price, F, K, r, t, flag)    
#     df10.loc[i:i+n,'iv'] = df10.loc[i:i+n].apply(lambda r:mibian.BS([r.close_y,r.strike,2,r.dte], callPrice=r.close_x).impliedVolatility,axis=1)
    
print(f'doing remaining {datetime.datetime.now()}')
i = df10[df10.iv.isna()].index[0]
# df10.loc[i:,'iv'] = df10.loc[i:].apply(lambda r:mibian.BS([r.close_y,r.strike,2,r.dte], callPrice=r.close_x).impliedVolatility,axis=1)
if USE_PYVOL:
    df10.loc[i:,'iv'] = df10.loc[i:].apply(lam_pyvol,axis=1)
else:
    df10.loc[i:,'iv'] = df10.loc[i:].apply(lam_mbian,axis=1)

print(f'doing remaining {datetime.datetime.now()}')
display.display(df10.head())
display.display(df10.tail())

#100% 13/13 [00:41<00:00, 3.20s/it]

HBox(children=(IntProgress(value=0, max=13), HTML(value='')))

/Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages/pandas/core/indexing.py:362: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

/Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

doing remaining 2019-07-03 14:28:15.444965
doing remaining 2019-07-03 14:28:15.544468

,symbol,settle_date,pc,contract_num,strike,close_x,close_y,dte,iv
0,CLM15,20150323,C,2,35.0,14.48,49.15,52,0.644413
1,CLM15,20150323,C,2,40.0,10.02,49.15,52,0.579568
2,CLM15,20150323,C,2,41.0,9.19,49.15,52,0.568698
3,CLM15,20150323,C,2,42.0,8.38,49.15,52,0.557028
4,CLM15,20150323,C,2,43.0,7.60,49.15,52,0.546118

,symbol,settle_date,pc,contract_num,strike,close_x,close_y,dte,iv
1393,CLM15,20150421,C,2,72.0,0.03,56.61,23,0.428059
1394,CLM15,20150421,C,2,72.5,0.03,56.61,23,0.438507
1395,CLM15,20150421,C,2,73.0,0.03,56.61,23,0.448844
1396,CLM15,20150421,C,2,73.5,0.02,56.61,23,0.435989
1397,CLM15,20150421,C,2,74.0,0.02,56.61,23,0.445728

In [680]:
# df10_save_mbian = df10.copy()
# df10_save_pyvol = df10.copy()
print(df10_save_mbian.shape,df10_save_pyvol.shape)
display.display(df10_save_mbian.head())
display.display(df10_save_pyvol.head())

(1398, 9) (1398, 9)

,symbol,settle_date,pc,contract_num,strike,close_x,close_y,dte,iv
0,CLM15,20150323,C,2,35.0,14.48,49.15,52,58.105469
1,CLM15,20150323,C,2,40.0,10.02,49.15,52,54.931641
2,CLM15,20150323,C,2,41.0,9.19,49.15,52,54.321289
3,CLM15,20150323,C,2,42.0,8.38,49.15,52,53.466797
4,CLM15,20150323,C,2,43.0,7.60,49.15,52,52.734375

,symbol,settle_date,pc,contract_num,strike,close_x,close_y,dte,iv
0,CLM15,20150323,C,2,35.0,14.48,49.15,52,0.644413
1,CLM15,20150323,C,2,40.0,10.02,49.15,52,0.579568
2,CLM15,20150323,C,2,41.0,9.19,49.15,52,0.568698
3,CLM15,20150323,C,2,42.0,8.38,49.15,52,0.557028
4,CLM15,20150323,C,2,43.0,7.60,49.15,52,0.546118

In [681]:
# define amounts around the money which will help create strikes to add
moneyness = np.arange(.7,1.4,.05).round(6)
# define columns on which to execute groupby
gb_cols = ['symbol','settle_date','pc','contract_num','dte','close_y']
# define function used in groupby.apply to create strikes and iv's at those strikes
#   where the strikes are an even amount from the money 
#   (like .7, .8, ... 1, 1.1, 1.2, etc)
def _add_even_money_strikes(df):
    # get underlying from first row (the groupby makes them all the same)
    r = df.iloc[0]
    underlying = r.close_y
    # create new rows to append to df, using only the gb_cols
    df_ret1 = df.iloc[:len(moneyness)][gb_cols]
    # add nan iv's !!!! MUST BE np.nan - NOT None
    df_ret1['iv'] = np.nan
    # add new strikes
    df_ret1['strike'] = moneyness * underlying
    # append the new strikes
    df_ret2 = df.append(df_ret1,ignore_index=True).sort_values(['symbol','settle_date','pc','strike'])
    df_ret2 = df_ret2.drop_duplicates(subset='strike')
    # set the index to the strike so that interpolate works
    df_ret2.index = df_ret2.strike
    # create interpolated iv's
    df_ret2['iv'] = df_ret2.iv.interpolate(method='polynomial', order=2)
    # reset the index
    df_ret2.index = list(range(len(df_ret2)))
    return df_ret2


df11 = df10.groupby(gb_cols).apply(_add_even_money_strikes)
df11.index = list(range(len(df11)))
df11['moneyness'] = (df11.strike / df11.close_y).round(6)

df12 = df11[(df11.moneyness.isin(moneyness)) & (~df11.iv.isna())]
df12.moneyness  = df12.moneyness - 1
df12.index = list(range(len(df12)))
df12_atm = df12[df12.moneyness==0][['symbol','settle_date','pc','iv']]
df12_atm = df12_atm.rename(columns={'iv':'atm_iv'})
df12_atm = df12_atm.drop_duplicates()
df12 = df12.merge(df12_atm,on=['symbol','settle_date','pc'],how='inner')
df12.moneyness = df12.moneyness.round(6)
df12['vol_skew'] = (df12.iv - df12.atm_iv).round(4)
df12[['symbol','settle_date','moneyness','vol_skew']]

/Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages/pandas/core/frame.py:6692: FutureWarning:

Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.


/Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages/pandas/core/generic.py:5096: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

    symbol  settle_date  moneyness  vol_skew
0    CLM15     20150323      -0.25    0.1429
1    CLM15     20150323      -0.20    0.1122
2    CLM15     20150323      -0.15    0.0846
3    CLM15     20150323      -0.10    0.0565
4    CLM15     20150323      -0.05    0.0289
5    CLM15     20150323       0.00    0.0000
6    CLM15     20150323       0.05   -0.0235
7    CLM15     20150323       0.10   -0.0440
8    CLM15     20150323       0.15   -0.0602
9    CLM15     20150323       0.20   -0.0711
10   CLM15     20150323       0.25   -0.0716
11   CLM15     20150323       0.30   -0.0676
12   CLM15     20150323       0.35   -0.0609
13   CLM15     20150324      -0.25    0.1309
14   CLM15     20150324      -0.20    0.1010
15   CLM15     20150324      -0.15    0.0748
16   CLM15     20150324      -0.10    0.0504
17   CLM15     20150324      -0.05    0.0261
18   CLM15     20150324       0.00    0.0000
19   CLM15     20150324       0.05   -0.0253
20   CLM15     20150324       0.10   -0.0464
21   CLM15     20150324       0.15   -0.0649
22   CLM15     20150324       0.20   -0.0743
23   CLM15     20150324       0.25   -0.0784
24   CLM15     20150324       0.30   -0.0728
25   CLM15     20150324       0.35   -0.0672
26   CLM15     20150325      -0.30    0.1785
27   CLM15     20150325      -0.25    0.1425
28   CLM15     20150325      -0.20    0.1071
29   CLM15     20150325      -0.15    0.0787
..     ...          ...        ...       ...
250  CLM15     20150417       0.05   -0.0173
251  CLM15     20150417       0.10   -0.0215
252  CLM15     20150417       0.15   -0.0131
253  CLM15     20150417       0.20    0.0060
254  CLM15     20150417       0.25    0.0413
255  CLM15     20150420      -0.30    0.2965
256  CLM15     20150420      -0.25    0.2122
257  CLM15     20150420      -0.20    0.1553
258  CLM15     20150420      -0.15    0.1067
259  CLM15     20150420      -0.10    0.0591
260  CLM15     20150420      -0.05    0.0280
261  CLM15     20150420       0.00    0.0000
262  CLM15     20150420       0.05   -0.0176
263  CLM15     20150420       0.10   -0.0265
264  CLM15     20150420       0.15   -0.0152
265  CLM15     20150420       0.20    0.0030
266  CLM15     20150420       0.25    0.0337
267  CLM15     20150421      -0.30    0.3062
268  CLM15     20150421      -0.25    0.2179
269  CLM15     20150421      -0.20    0.1471
270  CLM15     20150421      -0.15    0.1033
271  CLM15     20150421      -0.10    0.0621
272  CLM15     20150421      -0.05    0.0283
273  CLM15     20150421       0.00    0.0000
274  CLM15     20150421       0.05   -0.0200
275  CLM15     20150421       0.10   -0.0286
276  CLM15     20150421       0.15   -0.0212
277  CLM15     20150421       0.20    0.0006
278  CLM15     20150421       0.25    0.0329
279  CLM15     20150421       0.30    0.0483

[280 rows x 4 columns]

In [682]:
df12[df12.settle_date==20150327]

,close_x,close_y,contract_num,dte,iv,pc,settle_date,strike,symbol,moneyness,atm_iv,vol_skew
54,NaN,50.5,2,48,0.673809,C,20150327,35.350,CLM15,-0.30,0.482311,0.1915
55,NaN,50.5,2,48,0.631781,C,20150327,37.875,CLM15,-0.25,0.482311,0.1495
56,NaN,50.5,2,48,0.595144,C,20150327,40.400,CLM15,-0.20,0.482311,0.1128
57,NaN,50.5,2,48,0.563339,C,20150327,42.925,CLM15,-0.15,0.482311,0.0810
58,NaN,50.5,2,48,0.535172,C,20150327,45.450,CLM15,-0.10,0.482311,0.0529
59,NaN,50.5,2,48,0.507231,C,20150327,47.975,CLM15,-0.05,0.482311,0.0249
60,3.51,50.5,2,48,0.482311,C,20150327,50.500,CLM15,0.00,0.482311,0.0000
61,NaN,50.5,2,48,0.461618,C,20150327,53.025,CLM15,0.05,0.482311,-0.0207
62,NaN,50.5,2,48,0.444768,C,20150327,55.550,CLM15,0.10,0.482311,-0.0375
63,NaN,50.5,2,48,0.433194,C,20150327,58.075,CLM15,0.15,0.482311,-0.0491
64,NaN,50.5,2,48,0.433918,C,20150327,60.600,CLM15,0.20,0.482311,-0.0484
65,NaN,50.5,2,48,0.437509,C,20150327,63.125,CLM15,0.25,0.482311,-0.0448
66,NaN,50.5,2,48,0.447025,C,20150327,65.650,CLM15,0.30,0.482311,-0.0353
67,NaN,50.5,2,48,0.460264,C,20150327,68.175,CLM15,0.35,0.482311,-0.0220

### graph skew

In [683]:
settle_dates =  sorted(df12.settle_date.unique())
first_settle_date = settle_dates[0]
dfp = df12[df12.settle_date==first_settle_date][['moneyness','vol_skew']]
dfp = dfp.rename(columns={'vol_skew':str(first_settle_date)})
i=0
for s in settle_dates[1:]:
    dfp_this_s = df12[df12.settle_date==s][['moneyness','vol_skew']]
    dfp = dfp.merge(dfp_this_s,on='moneyness').rename(columns={'vol_skew':str(s)})
#     i+=1
#     if i>3:
#         break
display.display(dfp)
splits = list(np.arange(5,len(settle_dates),5))
settle_date_strings = [str(yyyymmdd) for yyyymmdd in settle_dates]
settle_date_groups = np.split(np.array(settle_date_strings),splits)
for sdg in settle_date_groups:
    cols = ['moneyness']+list(sdg)
    dfp_sub = dfp[cols]
    t = f'{contract} {list(set([c[:-2] for c in sdg]))}'
    iplot(plotly_plot(dfp_sub,x_column='moneyness',plot_title=t))

,moneyness,20150323,20150324,20150325,20150326,20150327,20150330,20150331,20150401,20150402,...,20150408,20150409,20150410,20150413,20150414,20150415,20150416,20150417,20150420,20150421
0,-0.25,0.1429,0.1309,0.1425,0.1389,0.1495,0.1483,0.1387,0.1421,0.1550,...,0.1764,0.1747,0.1847,0.1853,0.2055,0.1899,0.1943,0.2192,0.2122,0.2179
1,-0.20,0.1122,0.1010,0.1071,0.1047,0.1128,0.1106,0.1092,0.1066,0.1170,...,0.1251,0.1250,0.1333,0.1347,0.1487,0.1360,0.1379,0.1588,0.1553,0.1471
2,-0.15,0.0846,0.0748,0.0787,0.0758,0.0810,0.0784,0.0773,0.0753,0.0837,...,0.0888,0.0896,0.0952,0.0928,0.1038,0.0876,0.0884,0.1109,0.1067,0.1033
3,-0.10,0.0565,0.0504,0.0515,0.0494,0.0529,0.0507,0.0506,0.0471,0.0533,...,0.0568,0.0570,0.0597,0.0597,0.0624,0.0506,0.0488,0.0677,0.0591,0.0621
4,-0.05,0.0289,0.0261,0.0258,0.0251,0.0249,0.0240,0.0241,0.0217,0.0242,...,0.0273,0.0264,0.0292,0.0292,0.0279,0.0207,0.0219,0.0310,0.0280,0.0283
5,0.00,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
6,0.05,-0.0235,-0.0253,-0.0211,-0.0192,-0.0207,-0.0213,-0.0217,-0.0192,-0.0189,...,-0.0207,-0.0225,-0.0193,-0.0188,-0.0253,-0.0164,-0.0088,-0.0173,-0.0176,-0.0200
7,0.10,-0.0440,-0.0464,-0.0401,-0.0334,-0.0375,-0.0391,-0.0379,-0.0328,-0.0332,...,-0.0378,-0.0376,-0.0314,-0.0310,-0.0309,-0.0179,-0.0116,-0.0215,-0.0265,-0.0286
8,0.15,-0.0602,-0.0649,-0.0521,-0.0429,-0.0491,-0.0512,-0.0507,-0.0397,-0.0389,...,-0.0448,-0.0420,-0.0350,-0.0310,-0.0276,-0.0073,0.0003,-0.0131,-0.0152,-0.0212
9,0.20,-0.0711,-0.0743,-0.0563,-0.0435,-0.0484,-0.0573,-0.0558,-0.0391,-0.0405,...,-0.0443,-0.0411,-0.0259,-0.0243,-0.0104,0.0171,0.0223,0.0060,0.0030,0.0006
10,0.25,-0.0716,-0.0784,-0.0555,-0.0366,-0.0448,-0.0545,-0.0564,-0.0365,-0.0340,...,-0.0326,-0.0197,-0.0065,-0.0001,0.0162,0.0479,0.0562,0.0413,0.0337,0.0329

/Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages/plotly/graph_objs/_deprecations.py:396: DeprecationWarning:

plotly.graph_objs.Margin is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.Margin

In [558]:
for yyyymmdd in sorted(df12.settle_date.unique()):
    dfp = df12[df12.settle_date==yyyymmdd][['moneyness','skew']]
    iplot(plotly_plot(dfp,x_column='moneyness',plot_title=str(yyyymmdd)))

/Users/bperlman1/Virtualenvs3/pyliverisk/lib/python3.6/site-packages/plotly/graph_objs/_deprecations.py:396: DeprecationWarning:

plotly.graph_objs.Margin is deprecated.
Please replace it with one of the following more specific types
  - plotly.graph_objs.layout.Margin

In [529]:
# s = ['symbol','pc','settle_date','strike']
# dft = df10.append(df11,ignore_index = True).sort_values(s)
# dft['iv2'] = dft.iv.interpolate(method='polynomial', order=2)

# dft['skew'] = (dft.iv2 - dft.loc[v].imp2).round(4)
# dft['money'] = (dft.strike / dft.close_y - 1)
# dft.money = dft.money.round(4)
# dft[dft.index.isin(a)]

In [212]:
underlying=1.4565
strike=1.45
interest = 1
days=30
opt_info = [underlying,strike,interest,days]
c = mibian.BS(opt_info, volatility=20)
print(c.callPrice,
c.putPrice,
c.callDelta,
c.putDelta,
c.callDelta2,
c.putDelta2,
c.callTheta,
c.putTheta,
c.callRho,
c.putRho,
c.vega,
c.gamma)


co = mibian.BS(opt_info, callPrice=c.callPrice)
co.impliedVolatility

0.03721154839277063 0.029520257209636247 0.5481584196590104 -0.4518415803409897 -0.52495254471764 0.4742258751560606 -0.0005720853891507385 -0.0005323919998680845 0.000625628375211434 -0.0005651733032681817 0.0016536933299310715 4.742153534821618

20.000457763671875